# Generated by Django 3.2.10 on 2021-12-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenceinfo',
            options={'verbose_name': 'Ссылка для пользователя', 'verbose_name_plural': 'Ссылки для пользователей'},
        ),
        migrations.AddField(
            model_name='referenceinfo',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
